### ISSUE TITLE
Does this project support searching over multiple indexes?

### ISSUE THREAD

**Issue by Dirk-Kokx** [renoki-co/elasticscout#37]
I really like this integration of Elasticsearch in Scout, and was wondering if it is somehow possible to search over multiple indexes. In my case I would like to search over products and product-variations in different indexes and have the results ordered by importance.

There is a package that can do this, but it lacks features in other areas:
https://github.com/matchish/laravel-scout-elasticsearch#search-amongst-multiple-models

**Comment by rennokki** [comment]
This package is in the process of being deprecated. Prolly I'll archive it right now. Use [babenkoivan's elasticsearch plus package](https://github.com/babenkoivan/elastic-scout-driver-plus/blob/master/docs/generic-methods.md#join) for this feature.
